[project]
name = "ai-video-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepgram-sdk>=3.10.1",
    "jupyter>=1.1.1",
    "openai-whisper>=20240930",
    "python-dotenv>=1.1.0",
]
